# Generated by Django 5.0.2 on 2024-03-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='comentarios',
            field=models.TextField(blank=True, max_length=510),
        ),
    ]
