# Generated by Django 5.0.2 on 2024-03-06 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_', '0003_theme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='nombre_completo',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='nombre_completo',
            new_name='name',
        ),
    ]
