# Generated by Django 5.0.2 on 2024-03-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_', '0004_rename_nombre_completo_invitation_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='tema',
            new_name='song',
        ),
    ]
