# Generated by Django 5.0.2 on 2024-03-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_', '0005_rename_tema_theme_song'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invitation',
            old_name='asiste',
            new_name='assist',
        ),
        migrations.RenameField(
            model_name='invitation',
            old_name='comentarios',
            new_name='comments',
        ),
    ]
